# Generated by Django 5.2.7 on 2025-11-02 15:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('crop_id', models.AutoField(primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('Kenya', 'Kenya'), ('Other', 'Other')], max_length=20)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('extension_officer', 'Extension Officer'), ('researcher', 'Researcher')], max_length=20)),
                ('consent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CropDisease',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=100)),
                ('disease_characteristics', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='core.crop')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseTreatment',
            fields=[
                ('drug_id', models.AutoField(primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=100)),
                ('drug_administration_instructions', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='core.crop')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='core.cropdisease')),
            ],
        ),
    ]
