# Generated by Django 5.2.7 on 2025-11-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='description',
        ),
    ]
