# Generated by Django 5.2.7 on 2025-11-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_crop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
