# Generated by Django 5.2.7 on 2025-11-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_crop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropdisease',
            name='prevention',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropdisease',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropdisease',
            name='disease_characteristics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
