# Generated by Django 5.2.7 on 2025-11-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20251120_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropdisease',
            name='disease_characteristics',
        ),
    ]
